src/accounts/urls.py
from accounts.views import (AccountChangePasswordView,
                            AccountCreateView,
                            AccountListView,
                            AccountLoginView,
                            AccountLogoutView,
                            AccountUpdateView,)

from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path('register/', AccountCreateView.as_view(), name='register'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('account/', AccountUpdateView.as_view(), name='account'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('password/', AccountChangePasswordView.as_view(), name='password'),
    path('account_list/', AccountListView.as_view(), name='account_list'),
]

src/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('core.urls')),

    path('testify/', include('testify.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

src/core/urls.py
from core.views import index

from django.urls import path


app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
    ]

src/testify/urls.py
from django.urls import path

from testify.views import TestListView

app_name = 'testify'

urlpatterns = [
    path('tests', TestListView.as_view(), name='tests_list'),
    ]

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    {% block title %}
    <title>TESTIFY</title>
    {% endblock %}
</head>




<body>


<nav class="navbar navbar-expand-lg navbar-dark p-3 mb-2 bg-dark text-white">
  <div class="container">
  <a class="navbar-brand" href="{% url 'core:index' %}">TESTIFY</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"  aria-pressed="true">
    <span class="navbar-toggler-icon"></span>
  </button>


        <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item ">

          {% url 'testify:tests_list' as top_path %}
          {% if top_path == request.path %}
          <a class="nav-link active"  href="{% url 'testify:tests_list' %}">Tests<span class="sr-only">(current)</span></a>
          {% else%}
          <a class="nav-link "  href="{% url 'testify:tests_list' %}">Tests<span class="sr-only">(current)</span></a>
          {% endif %}
      </li>

        <li class="nav-item ">

          {% url 'accounts:account_list' as top_path %}
          {% if top_path == request.path %}
          <a class="nav-link active"  href="{% url 'accounts:account_list' %}">Leaderboard<span class="sr-only">(current)</span></a>
          {% else%}
          <a class="nav-link "  href="{% url 'accounts:account_list' %}">Leaderboard<span class="sr-only">(current)</span></a>
          {% endif %}
      </li>

</ul>
     </div>


      <ul class="navbar-nav ">
          {% if user.is_authenticated%}
          <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:account' %}">Account ({{user.username}})</a>
        </li>
<!--             <div class="media">-->
<!--            <div class="img-circle.vert">-->
<!--    <img class="rounded-circle p-1 mb-0 " width="40" height="40" src="{{ user.profile.image.url }}" >-->
<!--  </div>-->
<!--  </div>-->
              <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:logout' %}">Log out</a>
      </li>

        {% else%}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
      </li>
              <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
      </li>

              {% endif %}
    </ul>

  </div>
</nav>
    <div class="container">
        {% include 'includes/messages.html' %}


        <div class=" border-0 rounded-bottom text-center h-3 p-2 mb-2 bg-secondary text-white shadow-lg p-3 mb-5 rounded">
            {% block header %}
            <h1>
                Welcome to TESTIFY!
            </h1>

        {% endblock %}

    </div>





          {% block content %}

          {% endblock %}



    </div>

</body>
</html>

src/templates/index.html
{% extends 'base.html' %}
{% block content %}

{% endblock %}

src/templates/paginator.html
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}&{{ request.query_params }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}&{{ request.query_params }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>